Added an example
hierynomus/smbj pull request #461
Opened 2019-05-02 17:50 UTC by MattBrou

Took me a while to figure out how to properly read a file with SMBJ library. So I thought I'd share my solution.

2019-07-10 02:51 UTC, jerrychong25 commented
Yes, I agree with to add a example on how to read & write file.

As documentation did not mentioned about it.

2019-07-10 03:36 UTC, jerrychong25 commented
@MattBrou,

Do you have a example on how to write new content into file after read a file?

Flow:
Read File -> Add New Content -> Write File -> Save File

2020-01-31 13:40 UTC, hierynomus requested changes

2020-01-31 13:40 UTC, hierynomus commented on README.adoc
> +            return content;
You should also nest the `share.openFile` in a try-block, as the `File` object needs a close to release.
And don't forget to properly close the `smbFileRead.getInputStream()`

2026-06-18 14:26 UTC, closed without merging